### ISSUE TITLE
yarn kickstart fails for NodeJs > v14

### ISSUE THREAD

**Issue by stsydow** [freesewing/freesewing#1708]
### Tasks
 
- [x] We should have something in the README / *Getting started* that says.
  ```
  You need NodeJS  lts/fermium (v14.8.*), consider too use _nvm_.  
  ```
  because v14.7 is also to low.
- [ ] The designer tutorial at 
https://freesewing.dev/tutorials/pattern-design
also needs an update, as it suggests that any version is fine.
- [ ] Same goes for the developer docs:
https://freesewing.dev/tutorials/getting-started-linux/installing-node

### Original Thread

running `yarn kickstart` fails with:
```
yarn run v1.22.17
$ npx lerna bootstrap && npm run buildall
npm ERR! code EDUPLICATEWORKSPACE
npm ERR! must not have multiple workspaces with the same name
npm ERR! package 'freesewing.dev' has conflicts in the following paths:
npm ERR!     /home/st/Dokumente/privat/freesewing/packages/freesewing.dev
npm ERR!     /home/st/Dokumente/privat/freesewing/packages/freesewing.lab

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/st/.npm/_logs/2022-01-23T13_22_59_006Z-debug-0.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm clone the repo just now and did no changes.
Yarn and node are preinstalled and I run Arch Linux.

Full log
```log
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'lerna',
0 verbose cli   'bootstrap'
0 verbose cli ]
1 info using npm@8.3.2
2 info using node@v17.3.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/home/st/Dokumente/privat/freesewing/.npmrc Completed in 2ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/st/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 14ms
19 timing npm:load:configload Completed in 14ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 3ms
22 timing npm:load:display Completed in 5ms
23 verbose logfile /home/st/.npm/_logs/2022-01-23T13_22_59_006Z-debug-0.log
24 timing npm:load:logFile Completed in 5ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 24ms
28 silly logfile start cleaning logs, removing 1 files
29 http fetch GET 200 https://registry.yarnpkg.com/lerna 467ms (cache miss)
30 timing arborist:ctor Completed in 1ms
31 timing command:exec Completed in 647ms
32 verbose stack Error: must not have multiple workspaces with the same name
32 verbose stack package 'freesewing.dev' has conflicts in the following paths:
32 verbose stack     /home/st/Dokumente/privat/freesewing/packages/freesewing.dev
32 verbose stack     /home/st/Dokumente/privat/freesewing/packages/freesewing.lab
32 verbose stack     at getError (/usr/lib/node_modules/npm/node_modules/@npmcli/map-workspaces/lib/index.js:65:24)
32 verbose stack     at mapWorkspaces (/usr/lib/node_modules/npm/node_modules/@npmcli/map-workspaces/lib/index.js:123:17)
32 verbose stack     at async Arborist.[loadWorkspaces] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-workspaces.js:22:24)
32 verbose stack     at async Arborist.[loadActualActually] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-actual.js:181:5)
32 verbose stack     at async exec (/usr/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:123:16)
32 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:66:5)
33 verbose cwd /home/st/Dokumente/privat/freesewing
34 verbose Linux 5.16.2-arch1-1
35 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "lerna" "bootstrap"
36 verbose node v17.3.0
37 verbose npm  v8.3.2
38 error code EDUPLICATEWORKSPACE
39 error must not have multiple workspaces with the same name
39 error package 'freesewing.dev' has conflicts in the following paths:
39 error     /home/st/Dokumente/privat/freesewing/packages/freesewing.dev
39 error     /home/st/Dokumente/privat/freesewing/packages/freesewing.lab
40 verbose exit 1
41 timing npm Completed in 989ms
42 verbose code 1
43 error A complete log of this run can be found in:
43 error     /home/st/.npm/_logs/2022-01-23T13_22_59_006Z-debug-0.log
```

**Comment by nicholasdower** [comment]
Hi @stsydow can you try syncing? This might have been fixed by https://github.com/freesewing/freesewing/pull/1702.

**Comment by nicholasdower** [comment]
The commit is [d9678905cb5b58780044e4dccc30a23dc64dda03](https://github.com/nicholasdower/freesewing/commit/d9678905cb5b58780044e4dccc30a23dc64dda03).

FYI, I just tried to repro and was unable to.

**Comment by stsydow** [comment]
Yes, one step further:
```log
yarn run v1.22.17
$ npx lerna bootstrap && npm run buildall
Need to install the following packages:
  lerna
Ok to proceed? (y) 
lerna notice cli v4.0.0
lerna notice filter excluding "component-*"
lerna info filter [ '!component-*' ]
lerna info bootstrap root only
[1/4] Resolving packages...
[2/4] Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
error strapi@3.6.8: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "17.3.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock exited 1 in 'root'
lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock exited 1 in 'root'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nicholasdower** [comment]
Great! What node version are you one? You might need to change it. See https://freesewing.dev/tutorials/getting-started-linux/node-versions.

I am on:
```shell
> node -v
v14.18.2
```

**Comment by nicholasdower** [comment]
Oh I see it in the original logs:
```
node@v17.3.0
```

Can you try installing 14.x.x?

**Comment by nicholasdower** [comment]
I see 14.18.3 is latest:
```shell
->     v14.18.2   (LTS: Fermium)
       v14.18.3   (Latest LTS: Fermium)
```

So:
```shell
nvm install v14.18.3
nvm use v14.18.3
```

**Comment by stsydow** [comment]
I need the current installation, so that is not so easy.
So I figured strapi@3.6.8 needs nodejs <= v14 and the last release 4.0.5
is for node <= v16.

I will try to find a way to run Node v14 but wonder how to upgrade and test strapi.

**Comment by nicholasdower** [comment]
> I need the current installation, so that is not so easy. So I figured strapi@3.6.8 needs nodejs <= v14 and the last release 4.0.5 is for node <= v16.
> 
> I will try to find a way to run Node v14 but wonder how to upgrade and test strapi.

I don't know how to upgrade Strapi (I've never heard of it until just now), but I'd also like to know about this.

This seems like a perfect conversation for [#development-help](https://discord.com/channels/698854858052075530/698862765053575188) in Discord. How do you feel about asking over there?

**Comment by joostdecock** [comment]
I'm AFK right now but here's some thoughts:

- with nvm switching node versions is easy. The current monorepo works with `nvm use lts/fermium`
- Upgrading strapi is on my todo list, but since it's a new major version, we need to check the breaking changes

nvm lives here: https://github.com/nvm-sh/nvm

**Comment by joostdecock** [comment]
From: https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides.html#instructions

> At the moment there are no migration guides from v3-Stable to v4-Stable. These will be coming soon!

:shrug:

**Comment by joostdecock** [comment]
> I will try to find a way to run Node v14 but wonder how to upgrade and test strapi.

@stsydow As mentioned above, the strapi migration guide is still missing (seemingly it's being worked on).

However, strapi has dropped support for MongoDB in v4, which happens to be the database we are using.
The [list of supported databases](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/cli.html#preparing-the-installation) is now:

- SQLite
- PostgreSQL
- MySQL
- MariaDB

So this migration will take some work/planning. Might be easier to setup a new instance, then port our content somehow.

The current database runs on our backend server (we also use mongo for the freesewing user accounts and so on).
Rather than spinning up and extra database server, perhaps we could/should use a cloud offering. I think strapi is a pretty good candidate since it's only used at build time (well that and the admin UI).
There's probably a free tier out there that might cover our needs, but I'm open to other suggestions as well.

When you say *wonder how to upgrade and test strapi* I'm not sure that this is what you had in mind, but if you're interested, I'd be happy to see how we can make that happen.

Until strapi is upgraded/migrated, I guess node v17 support will prove tricky. Furthermore I'm not sure that strapi is the only blocking factor as we have some modules that are being held back because their new major version are ESM-only, and migration to ESM-only for FreeSewing is on the v3 roadmap (as it's a breaking change).

The list of ESM-only dependencies being held back is here: https://github.com/freesewing/freesewing/discussions/1685


Given that this will be a non-trivial migration, I'm not sure how useful it is to keep this issue open. :thinking:

**Comment by stsydow** [comment]
Ok I got node v14.8.7 via `nvm` and and `yarn kickstart` went through. 

I wanted to edit a pattern (Brian) and try it out, 
but there is no `yarn start` at top level and in the pattern it will just build and not start a local webserver.

You may as well close the issue, but a guess some hints in the documentation would help (I can try later): 
- [ ] We should have something in the README / *Getting started* that says.
```
You need NodeJS  lts/fermium (v14.8.*), consider too use _nvm_.  
```
because v14.7 is also to low.
- [ ] The designer tutorial at 
https://freesewing.dev/tutorials/pattern-design
also needs an update, as it suggests that any version is fine.
- [ ] Same goes for the developer docs:
https://freesewing.dev/tutorials/getting-started-linux/installing-node

**Comment by joostdecock** [comment]
Thanks for the feedback, the documentation needs to be updated, clearly.

To spin up brian, run `yarn install` followed by `yarn start` in `packages/brian/example`

I'm working on a new development environment that is optimized for working with (in) our monorepo.
The current development environment is geared towards people who run `npx create-freesewing-pattern` and that's typically the use-case our docs cover.

The problem of course is that this only makes sense for people starting a new pattern, not for hacking existing designs.

But we're working on it 🤞

**Comment by stsydow** [comment]
OK that worked with a hint from discord.

So for the record:
yarn start gave
```log
yarn run v1.22.17
$ react-scripts start

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  .../freesewing/node_modules/babel-loader (version: 8.2.3) 

Manually installing incompatible versions is known to cause hard-to-debug issues.
...
If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!
```

So I did that. In an other project we fixed it by adding the following to the package.json:
``` yaml
    "resolutions": {
      "babel-loader": "8.1.0"
    },
```
This is because react-scripts like only a specific version of babel.

But in the monorepo I don't know where this place would be.

**Comment by nicholasdower** [comment]
Going to close this as I believe the original bug has been fixed. Please feel free to reopen.
