### ISSUE TITLE
:open_umbrella: FreeSewing.org | v3 issues/todo

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#4071]
This is an umbrella issue to capture all work that needs to happen on the v3 version of **FreeSewing.org** prior to a v3 release.

If you find something missing, you can comment on this issue and we'll add it.

### Postponed
- [ ] Add linedrawings in artwork as React components so they can be used in the pattern overview pages
- [ ] The new options pack thing
- [ ] Add QR code to PDF for long-ass URL
- [ ] Extend draft log view to handle more common errors
   - [ ] *The most common error that I see/make is when I try to use a Point/Path that doesn't exist because of a typo or slightly incorrect camelCase in the name I used.* (@BenJamesBen )
   - [ ] Passing a non-Point to something that expects a Point (like passing coordinated to `path.move()`)
- [ ] Scratch codes when enabling MFA
- [ ] Adding the several new patterns that are sitting in a PR

## Resolved
- [x] Support for bookmarking:
  - [x]  sets
  - [x] patterns
  - [x] docs
- [x] Curated sets picker & bookmarked set picker
- [x] Add cover art, plus links to design documentation and showcase to Design pages (no cover art in v3)
- [x] Improve paperless view in dark mode (and perhaps other themes, as the draft themeing is somewhat different from the rest of the site)
- [x] Extend designs software config file with techniques based on work done in #880 and add to filtering in design list
- [x] The recent changes to the header have caused the offset of anchor links to be incorrect. 
- [x] Design filtering
- [x] Hide set checkbox when there are no sets
- [x] Implement newsletter signup pages
- [x] The macro work Wouter did in #3998 
- [x] Add the waist to armpit measurement and adapt various patterns to use it
- [x] Make annotations store IDs in store
- [x] Make 'complete' stuff more automatic (not shown when complete is off, with option to override)
- [x] Make title plugin create a map of partname/nr so we can show the nr in the included parts list
- [x] Implement translation method in plugin-i18n (for people who just want to pass in data)
- [x] Implement OIDC/login with Google
- [x] Implement OIDC/login with GitHub
- [x] Inline docs don't have custom components enabled / or they are broken (fixed by @eriese in #4864 )
- [x] Accessible colors in all themes
- [x] Implement changes in #4255 for all designs and adapt UI to handle translation of designs
- [x] text labels on navigation header are not shown on smaller window sizes (reported by @BenJamesBen wnd fixed by @joostdecock )
- [x] log view is not implemented (yet) (reported by @BenJamesBen and fixed by @joostdecock )
- [x] #4272 
- [x] *It is inconvenient having the Control setting available only in Draft. I ended up in Printing Layout, looking for a way to change margin size, cover page, etc, but these options were missing (because of my Control level) and there wasn't an obvious way to get them to appear. Another reason to just switch to Level 5.* (@BenJamesBen )
Fixed as part of the newly implemented workbench menu (@joostdecock )
 - [x] *This might just be a familiarity issue, but it is difficult to determine where in the navigation I am currently, just by looking at the navigation bar. It might be helpful to have the Cutting Layout icon dimmed in the navigation bar if I am currently in the Cutting Layout screen. Or, some other way to designate where I am.* (@BenJamesBen )
Fixed in the new workbench view menu (@joostdecock )
- [x] *Measurements Sets symbol:  Recommend changing it to something like a ruler or Measuring tape as the drafting arm is something that is more relevant to architecture than sewing. It also unfortunately gives the image of forceps.* (@bobgeorgethe3rd )
Not sure what a drafting arm is, but the icon represents a caliper which was used to measure things in ol' times. That being said, I've replaced it with a new icon. I assume it's ok, if not let me know (@joostdecock )
- [x] *Theme, Language & Search: I feel these 3 should always be on the top menu. When you are in a generated design these are not present and it would be useful to have them if you need to switch language or theme without having to go back a page.* (@bobgeorgethe3rd )
This is no longer the case with the new workbench menu (@joostdecock )
- [x] *Measurements: A good thing to add back would be Manual measurement input like it is in lab 2.5, This will allow people to make a pattern without an account but also will allow users to tweak their measures on the fly when trouble shooting fit issues.* (@bobgeorgethe3rd )
The view has been added to the menu, although it's not implemented yet. That being said, it will serve only to adapt measurements. I don't think we'll implement the *enter your measurements manually* feature because I'd rather add the possibility to load them from a URL (@joostdecock )
- [x] *A Measurements tab on generated design page like lab 2.5 so Measurements can be changed and altered without leaving the generated design page. This would allow again people tweak on the fly and people to change measures without having to navigate backwards* (@bobgeorgethe3rd )
I think the entry above covers this (@joostdecock )
- [x] #4129 
- [x] *Settings and Measurements seem to clear/reset themselves when I go to a different web page and then back to the lab. But, I think this might be the new, expected behavior?* (@BenJamesBen)
It is indeed. Saving things in local storage was a required side-effect of having no way to load measurements, but that's no longer the case. Do note however that settings are persisted in the URL. So if you reload the page or navigate away and then use the back button of your browser to come back, they will be kept (@joostdecock )
- [x] Implement persistent state for settings in the workbench (kept in URL by @joostdecock )
- [x] redesign the workbench menu to allow more one-click access to commonly used features (see draft/test view top navigation by @joostdecock )
- [x] Skip measurements page for designs that have no measurement (taken care of by the way we load measurements in the workbench now, and only when needed, by @joostdecock and @eriese )
- [x] add a way to clear settings when drafting a pattern (reported by @BenJamesBen ) #4332
- [x] Implement blog posts / blog post overview #4305 AND #4331
- [x] Implement showcase posts / showcase posts overview #4305 AND #4331 
- [x] *I would recommend another horizontal line in the right menu between print layout options and design options, the same way there is a line between the design options and the core options. To make things easier to see.* (reported by @BenJamesBen ) #4332
- [x] When Seam Allowance is enabled, the UI says that the default seam allowance that is being applied is 1 cm. However, actually only a 5 mm seam allowance is applied to the pattern. This is confirmed in the YAML. And, selecting the reset button changes the UI seam allowance back to 1 cm, but the color is still magenta indicating a non-default value. (I think that there might be 2 different default values in the code.) (reported by @BenJamesBen ) #4332
- [x] Fewer clicks in the test view
- [x] Not all showcases on Strapi have been imported (they have now by @joostdecock )
- [x] Setup crowdin for new translation files
- [x] Mobile support for the main navigation menu #4342 
- [x] #4343
- [x] The `updatedMeasurements` toast added by @eriese to the workbench when loading measurements is the message we present to users when they have updated the measurements in their account. As such, I think it's misleading. I had a near panic because I was using a set of measurements that took me a long time to get and I hadn't backed them up. So if we're going to send a toast it should say something like `loadedMeasurements` or `appliedMeasurements` instead to avoid confusion.
- [x] The pan/zoom in the workbench does not use the entire viewport height (#4342)
- [x] Measurements View #4320 And #4330 
- [x] Reset Zoom button  (you can toggle the render engine to get the same effect) #4332
- [x] Design home page Certainly not perfect, but it's there. (@joostdecock )
- [x] Implement patron view/enroll pages. Done (@joostdecock )
- [x] Look into switching to Stripe as payment processor. I implemented the initial Stripe flow, but then hit a dead-end when it came to taxation. It's an obstacle I could not clear because FreeSewing is not a business and Stripe is not able or unwilling to handle such a use case. So, I reverted back to PayPal as payment processor, but I did change up the subscriptions plans and UI so that we have a pay-what-you-want model which is what I wanted.
- [x] Make it clear that newsletter is EN only. Actually, it's not (@joostdecock )
- [x] *With the browser window at just 50% width of my entire screen, the draft navigation menu disappears entirely. For example, I am unable to get to Edit or Print Layout.* (@BenJamesBen )
The cutoff to mobile needs to happen at some point, and that's at 1024px (@joostdecock )
- [x] *There doesn't seem to be a way to edit individual Measurements in the new lab. I miss this feature. (Edit YAML is a workaround.)* (@BenJamesBen ) There is now (@joostdecock )
- [x] *My perception is that the UI requires too many clicks to perform some actions. To toggle Cutting Layout grain direction, you need to click on Grain Direction to expose the choices and then select Vertical. and then possibly click again to hide the choices.* (@BenJamesBen ) I don't consider cutting layout something to block 3.0 over

**Comment by BenJamesBen** [comment]
(I'm not sure what the scope of this issue is, whether it is just for critical/necessary items or if it is for all general work. For example, does "Add Magde documentation" belong here?)

**Comment by BenJamesBen** [comment]
As requested, feedback on the new lab:

- With the browser window at over 75% of my entire screen, the text labels do not appear in the draft navigation top row menu, and it is difficult to see.
- With the browser window at just 50% width of my entire screen, the draft navigation menu disappears entirely. For example, I am unable to get to Edit or Print Layout.
- I don't see a way to clear all settings? No ClearThing equivalent?
- Settings and Measurements seem to clear/reset themselves when I go to a different web page and then back to the lab. But, I think this might be the new, expected behavior?
- 5 levels of Control is nice granularity, but I anticipate all customers simply automatically switching to level 5, regardless of what they actually might want or need. "I don't know what I might want or need, and I don't know which control level will gets me what, so it is safer to just jump to level 5."
- It is inconvenient having the Control setting available only in Draft. I ended up in Printing Layout, looking for a way to change margin size, cover page, etc, but these options were missing (because of my Control level) and there wasn't an obvious way to get them to appear. Another reason to just switch to Level 5.
- There doesn't seem to be a way to edit individual Measurements in the new lab. I miss this feature. (Edit YAML is a workaround.)
- This might just be a familiarity issue, but it is difficult to determine where in the navigation I am currently, just by looking at the navigation bar. It might be helpful to have the Cutting Layout icon dimmed in the navigation bar if I am currently in the Cutting Layout screen. Or, some other way to designate where I am.
- I would recommend another horizontal line in the right menu between print layout options and design options, the same way there is a line between the design options and the core options. To make things easier to see.

(I used the new lab to perform an actual, real-world task, to generate a custom Unice based on my measurements (using Edit YAML to load my measurements) and export the pattern to PDF. I'm actually making a Unice to help test the design.)

**Comment by eriese** [comment]
I've added some of the things that stood out to me from @bobgeorgethe3rd's [feedback](https://github.com/freesewing/freesewing/discussions/4257#discussioncomment-6140994). I think there's more in there that's worth putting on the list, but I ran out of steam

**Comment by joostdecock** [comment]
@eriese can we refrain from adding people's opinions/input to this list without them being vetted.

I  have removed the following after your edit:

- [ ] Keyboard-only accessibility in all menus
- [ ] Aria labels
- [ ] Fix appearance and usability of toggles
- [ ] Arrows on drop-downs
- [ ] Remove Bottom titles and buttons on dropdowns
- [ ] Move reset buttons next to the slider
- [ ] Persistent Settings

The first 2 because I don't consider them blocking factors for v3, the others because I disagree how the underlying issue should be addressed, or because I think it's the wrong approach.

That being said, there's others I've left in because they are good feedback. But I don't love the side-channel approach.

**Comment by eriese** [comment]
@joostdecock I didn't see it as side-channeling because that feedback is publicly available, but I can see that it being in a different place isn't preferable, so I'll close that discussion and copy Bob's comments here.

Once feedback is here, what's the actual vetting procedure? How many upvotes does something need to make the list even if you personally don't think it needs to be there?

For the items you removed because you think something else should happen, what do you think should be happening instead? It's frustrating to be told that you don't want side/back channels and then be told that items that you agree need addressing are not on the list because you have a private idea about how to address them

**Comment by joostdecock** [comment]
@eriese by side-channel I didn't mean that the discussion is in a different place. If discussions is more suitable for ... discussion, then that's fine I don't mind at all.
What I meant is that things are discussed over there and then added under *needs implementation* over here without being signed off. Which brings me to:

> *Once feedback is here, what's the actual vetting procedure? How many upvotes does something need to make the list even if you personally don't think it needs to be there?*

Nothing goes in without me signing off on it. So when I am not eager, the job is to convince me (as you've done more than once). Which you skipped here, and instead just added them to the list. That's the *side-channel* that I don't love.

> *For the items you removed because you think something else should happen, what do you think should be happening instead? It's frustrating to be told that you don't want side/back channels and then be told that items that you agree need addressing are not on the list because you have a private idea about how to address them*

Thank you for pointing out when things are frustrating, that's always good.
In general, I sometimes don't like things because they feel *patchy* to me. Like, the fix is too small in scope and instead we should re-think things. 
But then if somebody would advocate for a super-ambitious overhaul of a bunch of things, I am well aware that that would probably also make me nervous/reluctant.
I guess the point I'm trying to make is that at the end of the day, I sometimes don't feel comfortable with changes, even if I can't always rationally explain them. I appreciate that that is frustrating. But I don't have a solution for it.

Now in more practical terms:

- the first two, I'm all in favor for. I just don't want to hold up v3 for it
- I don't *love* those toggles. Or more precisely, I don't love how they look. I think it's a good addition from a functional point of view, but I don't like the esthetics of the implementation. So, I'd rather add a view-specific top-level navbar (below the main navbar) that has the one-click button for those toggles, and we keep the sidebar toggle-free. But that's just a vague idea so I'm not really sure how/what to do. But I think that however frustrating that is, it's less frustrating than doing work on something to then see that being replaced by something else.
- Others, I just fundamentally disagree with. Like moving reset buttons next to the slider. That's just *who moved my cheese* stuff IMHO.

**Comment by eriese** [comment]
Ok, I think I understand the parameters better now. Maybe we need a "needs ideas" category? I just don't want things to fall off the radar. I also don't want coming up with solutions and making design decisions to be solely your responsibility, both because it's a bottleneck and because it seems like we do now have some frontend people in the discord waiting to be directed toward some of this stuff and we could benefit from what they know.

side note: I think we can move "settings reset button" to "Nice to Have" given that you can achieve that outcome by refreshing the page. 

I also think that if we won't implement persistent settings, we should implement a leaving the page warning

**Comment by joostdecock** [comment]
@eriese please do, that would be great.

If you need help, let me know because we're migrating from strapi to sanity so the way we fetch the data needs to be updated.

**Comment by joostdecock** [comment]
@eriese Actually, if you rather not context-switch, I've just landed some changes and added the `measies` view which is supposed to allow people to tweak there measurements. So if you'd like, you could implement that view.

Best case scenario, it would:

- Allow users to quickly tweak a setting by dragging a slider (say +/- 10% of the current value or something)
- Allow users to manually input them (aka current lab behavior)
- Load a different set/cset/whatever of measurements

However, I feel these changes should be limited to the current scope. By which I mean, if I change a measurement from a measurement set in my account, it should not update the set in my account, but only here.

We may need to think about how we want to handle this state. Cram it into settings, or manage measurements differently (the way we have both `ui` and `settings` state anchored under the `update` object we pass down makes it kinda easy to keep it apart if we want to.

**Comment by joostdecock** [comment]
> *I also don't want coming up with solutions and making design decisions to be solely your responsibility, *

Believe it or not, neither do I :) But I really don't want to end up with a *design-by-committee* mess on our hands. 
So if there's somebody who wants to get really into this, great. My concern is the piece-meal fixes left and right that lack consistency.

Like, those collapse thingies in the sidebar are extensively used in the account management pages. And their behavior should be consistent (it's an example to illustrate the concern).

> *side note: I think we can move "settings reset button" to "Nice to Have" given that you can achieve that outcome by refreshing the page.*

I've moved it. But you can accomplish the same effect without losing state by toggling the React render engine on/off (I've also added this tip in the list above). And there's a button for that now on the draft and test views, so it's still 2 clicks instead of one, but ok :)

> I also think that if we won't implement persistent settings, we should implement a leaving the page warning

For persistent settings, I would prefer some sort of auto-save feature.
The reason is that persistent settings lead to hard to troubleshoot bugs, and if something breaks, it becomes a lot harder to back out of it.

Remember all of that save history and the going back to the previous settings that you implemented.
That's like a ton of complexity and I would really want to avoid that.

So to be clear: I am not against making settings reload-proof. But I am against using localStorage like we've been doing in the lab.

**Comment by eriese** [comment]
> @eriese Actually, if you rather not context-switch, I've just landed some changes and added the `measies` view which is supposed to allow people to tweak their measurements. So if you'd like, you could implement that view.

The blog pages are easy. I'm down to do both.

> 
> Best case scenario, it would:
> 
> * Allow users to quickly tweak a setting by dragging a slider (say +/- 10% of the current value or something)
> * Allow users to manually input them (aka current lab behavior)
> * Load a different set/cset/whatever of measurements

Sounds like it should reuse most of the new design page, plus sliders

> However, I feel these changes should be limited to the current scope. By which I mean, if I change a measurement from a measurement set in my account, it should not update the set in my account, but only here.

Agreed

> We may need to think about how we want to handle this state. Cram it into settings, or manage measurements differently (the way we have both `ui` and `settings` state anchored under the `update` object we pass down makes it kinda easy to keep it apart if we want to.

Definitely worth considering, though I think it adds more overhead than it removes because measurements have to be a property of settings when passed to the pattern constructor.

> My concern is the piece-meal fixes left and right that lack consistency.

This is why I made that big push for more shared components. Most changes should happen in one place and take effect everywhere. I hear you that you'd like things to happen intentionally, I just don't agree that saying "this thing is ugly, let's change it" is actually a piecemeal way of fixing things if it gets uniformly improved and the change is in line with the rest of the aesthetic

> So to be clear: I am not against making settings reload-proof. But I am against using localStorage like we've been doing in the lab.

Hmm, maybe the settings only get saved if there's no resultant error...

**Comment by joostdecock** [comment]
>  > So to be clear: I am not against making settings reload-proof. But I am against using localStorage like we've been doing in the lab.

> Hmm, maybe the settings only get saved if there's no resultant error...

Based on this *what if we only use localStorage when...* counter-offer, I seem to be doing a bad job of why I don't think localStorage is the way to go. 
My concern is that it means settings are being kept in something that is completely invisible to the user with no way to back out of whatever corner they paint themselves into. So we'd have to implement all sorts of *reset settings* or *go back to the previous settings* ourselves which we have been doing, but always felt hackish to me.

I guess I am just of the opinion that localStorage is a bad fit for this kind of state (as opposed to say something like `theme`).
Perhaps part of the reason why people are nostalgic for localStorage is because I took it out without offering an alternative. (for me it was just a matter of *we'll deal with it later*).

So, I've implemented settings state in the URL, and I am cautiously optimistic that people will realize this is a better way to handle this state.
For one thing, if a user makes a change that they don't like or breaks things, they can back out of it with something they already know: the browser's back button. 

This should also make it easy to override measurements in state, and make that state survive reloads or hot-reloads in the development environment.

**Comment by eriese** [comment]
I'm ok with that. We should definitely implement the in-ui back button, then. To get you back to your previous page without having to back through all your settings changes

**Comment by joostdecock** [comment]
I'm surprised you feel that way. I find the ability to *back* to a previous state a rather nice feature.

**Comment by eriese** [comment]
No, I completely agree that it's a great feature, and love that we won't have to manage history. I just also like to be able to get back to a previous *page* without having to back through my entire workflow, so a ui back button lets us have both

**Comment by joostdecock** [comment]
Ah, apologies. I misunderstood. Re-reading it now, that's on me. You were clear :shrug:

**Comment by eriese** [comment]
@joostdecock, I'd like to take on Reset Settings button, reset zoom button, and those line tweaks, that seam allowance bug, a few other tweaks, if you're not working on those things

**Comment by eriese** [comment]
just noticed in my mobile branch that the measies view can now take up the whole screen width and hide the workbench nav, and that the workbench nav bar doesn't extend being screen height even if the page does. 

I surely made those things happen, so I will fix them

**Comment by eriese** [comment]
needs implemented: user default settings merged with base settings. While right now I think it's just units, we may as well make it flexible now to accept other things down the road, like default seam allowance

**Comment by eriese** [comment]
#4393 refers to the "Compare" functionality, which I'm pretty sure is not implemented in v3. Should it be added to nice to have? or is it v3-critical?

**Comment by Cylarcher** [comment]
just discovered 2 problems with the measurements section: values entered as n/8 (like 30 7/8) won't save (and don't say anything about the failure), though when you enter 30.875 it will then display as 30 7/8.  Also, there's something wrong with the preview field for shoulder slope, looks like it might be an incorrect inch vs cm thing? 0.95blah is correct, I tested by generating a Simon
![20230704_091355](https://github.com/freesewing/freesewing/assets/55415375/61189c2f-61c7-46a5-ba6d-5099f6ff4bbe)

**Comment by lasermonkey12** [comment]
And a nice to have/opinion: I don't find the delete icon intuitive as the button to reset pattern parameters, I much prefer the circular thing used in v2

**Comment by lasermonkey12** [comment]
Bruce bulge adjustment slider is buggy, crashes display if you try to change it at all.  directly editing the number works though

**Comment by nataliasayang** [comment]
Question re "Add linedrawings in artwork as React components so they can be used in the pattern overview pages":

Some users are breaking up [46 Technical Drawing.svg](https://github.com/nataliasayang/freesewing/blob/develop/artwork/linedrawings/46%20Technical%20Drawing.svg) into the individual designs and editing the drawings.

Can you guide me on the best way to share the edited drawings? Is this okay? (Don't know if I did the `.jsx` thing correctly.) https://github.com/freesewing/freesewing/pull/4460

**Comment by joostdecock** [comment]
> Question re "Add linedrawings in artwork as React components so they can be used in the pattern overview pages":
> 
> Some users are breaking up [46 Technical Drawing.svg](https://github.com/nataliasayang/freesewing/blob/develop/artwork/linedrawings/46%20Technical%20Drawing.svg) into the individual designs and editing the drawings.
> 
> Can you guide me on the best way to share the edited drawings? Is this okay? (Don't know if I did the `.jsx` thing correctly.) #4460

You did very well @nataliasayang There's only a few things to fix (which is why I haven't merged it yet as I wanted to help out but was occupied doing other things).

I will comment on the pull request as that makes it easier to reference things.

**Comment by joostdecock** [comment]
@nataliasayang I have taken your (excellent) work and have adapted it so that we can get the most value out of it and hopefully can work towards consistency in line drawings.

The reason we're being so *difficult* is that we want linedrawings to be themeable. Here's an example of the Aaron linedrawing you made after I had my way with it:

![image](https://github.com/freesewing/freesewing/assets/1708494/b88b25f7-5815-4a7c-98b0-f14811a10b3d)

Same in dark mode:

![image](https://github.com/freesewing/freesewing/assets/1708494/008640bb-223f-4217-90eb-40dadebefac8)

To ensure this works, there's a few things to take into account:

- The only color allows is `currentColor`. That is a special placeholder the means the color will be inherited from the text color. This allows us to theme the linedrawing by setting something like `color-warning` or `color-accent` as a class on it. This is what results in the different coloured aarons in the screenshot above.
- We can only use `stroke` and no `fill`. You respected that but I'm adding it here for completion's sake
- No height or width on the SVG, only viewBox. This allows us to set the site in CSS (with classes) as the SVG will adapt to the size of the container
- Merge similarly styled paths together as one path object (that's just simpler/faster)
- I have also taken the liberty of creating an individual front/back view (in case we need it).
- Viewbox (as in, the size of the SVG) should be chosen so that a stroke="1" gives a good result. All stroke width should be a factor of the base stroke so that users can override it (as in the small green and pink examples above).

I appreciate that this extra step of going from SVG to a JSX in a way that allows all this is more work and perhaps not the most intuitive. I will make an effort to document this, but I'm also happy to do this myself if it's too much of a hassle.

For reference, the screenshot above is the result of:

```js
 import { Aaron, AaronFront, AaronBack } from 'shared/components/designs/linedrawings/aaron.mjs'
// ...
<div className='flex flex-row flex-wrap gap-4">
  <Aaron className="w-24 text-success" stroke={4}/>
  <Aaron className="w-64" />
  <Aaron className="w-48 text-accent" stroke={2}/>
  <Aaron className="w-96 text-primary" />
   <AaronFront className="w-96 text-error" />
   <AaronBack className="w-96 text-success" />
</div>
```

**Comment by eriese** [comment]
I'll take comma decimal separators

**Comment by joostdecock** [comment]
@SeaZeeZee might be worth it to verify with whomever added this (I don't know who it was) whether this is still an issue.

Themes saw some changes recently, in particular to ensure that things that previously were not themeable now are.

**Comment by joostdecock** [comment]
@SeaZeeZee might be worth it to verify with whomever added this (I don't know who it was) whether this is still an issue.

Themes saw some changes recently, in particular to ensure that things that previously were not themeable now are.

**Comment by bobgeorgethe3rd** [comment]
Not sure if it's still on the todo list or accidentally got dropped, but I'd like the line lengths back in the inspector view. I use this a lot in 2.5 and it's very useful to know lengths of paths and lines without having to use macros etc.

**Comment by lasermonkey12** [comment]
Measurements page will say that entries were saved, but they're not actually getting saved (also there's no default sets, so the only way to get patterns is to manually put in values)

Also I can't enter a negative armhole drop value, which is different from maybe a month ago.  It would be fine if 0 were right at the armpit, but it's lower than that and I want my armhole as short as I can get it

**Comment by lasermonkey12** [comment]
have there been thoughts about defaulting to letter size paper if the user has the default set to imperial vs a4 for metric?  Or actually, a user setting for the default paper size?  It didn't bother me to choose in v2 but in v3 the options now require a scroll and it's inefficient

**Comment by lasermonkey12** [comment]
found a bug in v3 letter paper export layout when I set the sleeve so it went off the left edge of the layout area.  It didn't happen with a4 paper and it resolved itself when I stopped trying to have the sleeve off the left edge (I'm making this one short sleeved, so I don't need the bottom of the sleeve)
[Uploading freesewing-simon-layoutBug.pdf…]()

**Comment by lasermonkey12** [comment]
Can the paperless numbers be displayed on top of all the other things in the pattern?  Like part numbers and the logo.  I ask this because it's not uncommon for measurement numbers to end up totally blocked and illegible.

**Comment by lasermonkey12** [comment]
measurement use/display problems:
measurements display in cm when looking at a measurement set, even if user has selected imperial units; is correctly in inches in edit view
'edit measurements by hand' also displays in cm when user has selected imperial
'edit measurements by hand' does not seem to save the edited measurement, just leaves the field empty and crashes the pattern (is there a save button missing?)
honestly I could probably save myself pain by switching to cm, but I already have a bunch of nice quilting rulers in inches.

**Comment by lasermonkey12** [comment]
carlita cutting layout is broken, I think the problem is in how the front/side pieces are handled.  I'm pretty sure I don't need over 14yd of fabric which is what is currently being suggested!
![image](https://github.com/freesewing/freesewing/assets/55415375/9e615680-efd2-48a8-b0a2-e02b89476337)

**Comment by lasermonkey12** [comment]
Print layout bug: if you include only some parts and customize the layout, the print layout will display only those parts until you reset the layout (ie if you choose more parts to be displayed they will not appear in the print layout)
steps to reproduce:
-generate a pattern, set it to include one or more parts (core settings>included parts)
-go to print layout and move pieces around
-go back to configure pattern layout, change your selection so that it includes at least one new part (you can keep or drop the previously selected parts)
-return to print layout, observe that the new parts are not present; if you removed all the parts you originally chose, print layout will be empty
-you can reveal these parts by going to layout settings>reset print layout
