### ISSUE TITLE
Contibutor call: September 19th 2020

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#553]
You are all invited to the contributor call.
Please leave a comment to put things on the agenda. This issue will be updated after the call with notes and todos.

## About

 - Location: https://meet.freesewing.org (redirects to https://zoom.us/j/5168598687 )
 - Date: Sep 19, 2020 16:00 UTC, which is:
   - Los Angeles: 09:00
   - Chicago: 11:00
   - New York: 12:00
   - São Paulo: 13:00
   - London: 17:00
   - Paris: 18:00
   - Johannesburg: 18:00
   - Moscow: 19:00
   - Mumbai: 21:30
   - Hong Kong: 00:00 on Sunday, September 6, 2020
   - Tokyo: 01:00 on Sunday, September 6, 2020
   - Sydney: 02:00 on Sunday, September 6, 2020

## Agenda

 - Completed ToDos:
   - [x] Schedule a new call 2 weeks from now #522 
   - [x] Setup a call with the community team #523
   - [x] Agree on a hashtag structure for our patterns #524
   - [x] Publish said hashtags prominently on the pattern pages and ask people to use them #525
   - [x] What platform should we use to coordinate collaboration? #530
   - [x] Compile a list of (patterns with) missing documentation #529
 - Ongoing ToDos:
   - [ ] Establish a *developer pool* that designers could call on to implement their patterns #526
   - [ ] Think about how collecting/sharing measurements could or would work #527
   - [x] Start (working on) a list of *roles* to fill #528
 - Ongoing ToDos:
   - [ ] Find people to fill those roles, or champion those topics #528
 - Call for volunteers for a *designer* call to focus on pattern-design related tasks
 - New website community pages & homepage: 
   - new homepage design with focus on contributors/patrons (preview at https://next.freesewing.org/ )
   - homepage link to revenue pledge
   - opt-in for contributors
   - what to put on community pages
   - where to publish open positions/roles. See #528
 - Free-form discussion

## Notes

 - Call started on time, with 10 or so participants (I forgot to count them) including 3 new faces: 
   - Sandra (@sewanista) who was joining us from Perth Australia and has a background in pattern design. It was her first time on the call, but she's been active with us both here on Github and on Discord
   - Sebastian who was joining us from Brazil and is doing research on (home) sewing and technology
   - Lisa who joined from the southern parts of the US and runs [Black women stitch](https://www.instagram.com/blackwomenstitch/)
   - Rachel who joined us from the US and has a background in sewing and is now learning to program
 - We went of the open/ongoing todos of the previous contributor call, of which you can find a summary in the agenda of this call
 - @joostdecock explained that there was some new content and home page on https://next.freesewing.org/ that still needed to be populated to reflect the actual list of contributors. This would be on an opt-in basis, so you can make that easier by proactively reaching out if you'd like to be featured.
 - Several people indicated an interest in joining a *pattern design* group to focus specifically on designing patterns for FreeSewing. Which includes pattern design itself, but also how to get them implemented on our platform. Rachel, Sandra, and Wouter were among those showing an interest.
 - @tangerineshark  indicated that she would be willing to help with writing (sewing) documentation
 - There was a lot of praise for [the video @creasyo made](https://youtu.be/b75VyR1dOoo) and for good reason
 - @creasyo made the case for working towards a *library* or different techniques that are used in sewing so that we can string together instructions in a more efficient way. (since many times, making a garment is stringing those techniques together in the right order.
 - @creasyo also warned that he was able to make the video because he had some extra (covid-related) downtime, but could not commit to this level of investment on a long-term basis. 
 - @joostdecock pointed out that when someone agrees to work on something or take up a task, we should always see that as a best-effort commitment. We cannot expect people to always follow through because life happens. Better to get people to take on ambitious plans that they half-complete than have them stand on the sidelines worried they won't be able to deliver.
 - Rached suggested that in the same vein of making videos about sewing techniques, it would be good to make similar videos for the coding/development aspects
 - An extended discussion sprung up about how to *translate* certain statically defined aspects of pattern drafting to a truly parametric draft.
 - We agreed to extend the designer docs with example of common challenges in sewing patterns and how to fix them in code (perhaps with videos)
 - Sandra has made some parametric designs in seamly/[valentina](https://valentinaproject.bitbucket.io/) and we could try to *port* one of her designs to FreeSewing
 - @creasyo asked when we would release Teagan. We still want to make a video of how to make Teagan with only a sewing machine (no serger) and finalize the new contributor content on the site.
 - Ultimately, we picked Saturday the 3rd of October as our release date. To make the happen, @joostdecock agreed to shoot the video the day after the call.
 - Before the end of the call, @joostdecock asked the new faces what they would hope to get out of their participation. Sebastian talked about his research and how he'd like to see how people with less access to technology or reliable power infrastructure could still benefit from the idea of a *WikiPedia for sewing patterns*
 - Sebastian also said that in the future, he'd like to help with Spanish and Portuguese translation
 - Lisa was unavailable at that time in the call, but @joostdecock will reach out to her to ask the same question
 - Unfortunately, I forgot to ask Rachel the same question, but I'm hoping she'll read this and let me know how to contact her
 - I also didn't ask Sandra, but while it was her first appearance on the call, she's @sewanista . So she's been around for a while and has written about what she hopes to accomplish in #527 

## Todo

 - Schedule a new call in 2 weeks: #561
 - Create a milestone for the Teagan release: https://github.com/freesewing/freesewing/milestone/10
 - Finalize new *community* focus on the website: #562
 - Setup a *pattern design* team to allow more in-depth focus on that particular topic: #563
 - Write Teagan documenation: #564
 - Compile a list of sewing techniques/steps that we want to document with video: #565
 - Shoot (#566) and edit (#567) a new Teagan video using only a regular sewing machine
 - Try making an initial coding video to figure out what works and what doesn't: #568
 - Compile a list of common coding challenges in sewing patterns: #569

As always, please share your updates or corrections in the comments

**Comment by eleonoremilbou** [comment]
Can't make it this time, sorry!

**Comment by joostdecock** [comment]
That's a pity, maybe next time :+1:

**Comment by joostdecock** [comment]
I'm closing this in favor of https://github.com/freesewing/freesewing/issues/561

But this is still the place to comment on the notes of this particular call

**Comment by rrolon47** [comment]
I am Rachel, sorry I didn't mention my screen name in the call.  As far as what I want to get out of participating... I am just really excited that there is a group of folks that are doing this in an open source way.  I would like to develop some patterns for FS, improve my coding and work collaboratively with coding.

**Comment by joostdecock** [comment]
Great to have you Rachel. You should receive an invite from github to join the freesewing organisation.
